from typing import Protocol


class Env(Protocol):
    def reset(self) -> list[str]: ...
    def step(self, actions: list[str]) -> tuple[list[str], list[float]]: ...
    def instructions(self) -> str: ...
